name: C/C++ CI
on:
  push:
    branches: [ emoji2 ]
  pull_request:
    branches: [ emoji2 ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
